- name: Install nginx and start nginx
  hosts: local
  become: yes
  tasks:
  - name: Install nginx
    ansible.buitltin.package:
     name: nginx
     state: installed

  - name: Start and enable nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enable: yes